name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # 15 14 * * * - 14:15 UTC every day
    - cron: 46 * * MON-FRI
  workflow_dispatch:

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: pepopowitz/merge-schedule-action@debugging
        with:
          time_zone: "America/Chicago"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
